/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        // Legacy tokens (kept for backward compat)
        ink: "#172033",
        line: "#d8dee8",
        field: "#f6f8fb",
        brand: "#155e75",
        success: "#0f766e",
        warn: "#b45309",
        danger: "#b91c1c",
        // Material Design tokens (from reference)
        "surface-container-low": "#f3f4f6",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#002106",
        "tertiary-fixed-dim": "#66df75",
        "error-container": "#ffdad6",
        "surface-container": "#edeef0",
        "surface-variant": "#e1e2e4",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "on-primary-container": "#ffe0f3",
        "on-primary-fixed": "#310e2b",
        "primary-fixed-dim": "#edb6dc",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#60d9d5",
        "on-background": "#191c1e",
        "tertiary-container": "#00792a",
        "surface-tint": "#7c5071",
        secondary: "#006a68",
        "on-primary-fixed-variant": "#623958",
        "outline-variant": "#d2c2ca",
        "surface-container-high": "#e7e8ea",
        "primary-container": "#875a7b",
        "on-secondary-fixed-variant": "#00504e",
        "inverse-surface": "#2e3132",
        "on-error-container": "#93000a",
        "primary-fixed": "#ffd7f1",
        "on-secondary-fixed": "#00201f",
        "on-secondary-container": "#006e6c",
        "tertiary-fixed": "#83fc8e",
        surface: "#f8f9fb",
        background: "#f8f9fb",
        error: "#ba1a1a",
        "inverse-on-surface": "#f0f1f3",
        tertiary: "#005d1e",
        "secondary-fixed": "#7ff5f1",
        "on-tertiary-fixed-variant": "#00531a",
        "on-surface": "#191c1e",
        "inverse-primary": "#edb6dc",
        outline: "#80747b",
        "surface-bright": "#f8f9fb",
        "on-surface-variant": "#4e444a",
        "on-tertiary-container": "#98ff9d",
        primary: "#6d4262",
        "secondary-container": "#7cf2ee",
        "surface-container-highest": "#e1e2e4",
        "surface-dim": "#d9dadc",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "0.75rem",
        full: "9999px",
      },
      spacing: {
        topbar_height: "64px",
        stack_sm: "8px",
        sidebar_width: "240px",
        gutter: "16px",
        container_padding: "24px",
        stack_md: "16px",
      },
      fontFamily: {
        sans: ["Nunito Sans", "ui-sans-serif", "system-ui", "sans-serif"],
        "display-lg": ["Nunito Sans", "sans-serif"],
        "label-bold": ["Nunito Sans", "sans-serif"],
        "body-base": ["Nunito Sans", "sans-serif"],
        "body-dense": ["Nunito Sans", "sans-serif"],
        "headline-md": ["Nunito Sans", "sans-serif"],
        "label-sm": ["Nunito Sans", "sans-serif"],
        "title-sm": ["Nunito Sans", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["30px", { lineHeight: "38px", fontWeight: "700" }],
        "label-bold": [
          "12px",
          {
            lineHeight: "16px",
            letterSpacing: "0.02em",
            fontWeight: "700",
          },
        ],
        "body-base": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-dense": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "600" }],
        "title-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
      },
      boxShadow: {
        panel: "0 1px 2px rgba(15, 23, 42, 0.06)",
        card: "0 4px 12px rgba(0,0,0,0.05), 0 2px 4px rgba(0,0,0,0.03)",
      },
    },
  },
  plugins: [],
};
